export default [
  { cdg: "01", name: "Crédito em Conta" },
  { cdg: "02", name: "Pagamento de Aluguel/Condomínio" },
  { cdg: "03", name: "Pagamento de Duplicata/Títulos" },
  { cdg: "04", name: "Pagamento de Dividendos" },
  { cdg: "05", name: "Pagamento de Mensalidade Escolar" },
  { cdg: "06", name: "Pagamento de Salários" },
  { cdg: "07", name: "Pagamento a Fornecedores" },
  { cdg: "08", name: "Operações de Câmbios/Fundos/Bolsa de Valores" },
  { cdg: "09", name: "Repasse de Arrecadação/Pagamento de Tributos" },
  { cdg: "10", name: "Transferência Internacional em Real" },
  { cdg: "11", name: "DOC para Poupança" },
  { cdg: "12", name: "DOC para Depósito Judicial" },
  { cdg: "13", name: "Outros" },
  { cdg: "16", name: "Pagamento de bolsa auxílio" },
  { cdg: "17", name: "Remuneração à cooperado" },
  { cdg: "18", name: "Pagamento de honorários" },
  {
    cdg: "19",
    name: "Pagamento de prebenda (Remuneração a padres e sacerdotes)",
  },
];
