export default [
  {
    cdg: "BTN",
    name: "Bônus do Tesouro Nacional + TR",
  },
  { cdg: "BRL", name: "Real" },
  { cdg: "USD", name: "Dólar Americano" },
  { cdg: "PTE", name: "Escudo Português" },
  { cdg: "FRF", name: "Franco Francês" },
  { cdg: "CHF", name: "Franco Suíço" },
  { cdg: "JPY", name: "Ien Japonês" },
  { cdg: "IGP", name: "Índice Geral de Preços" },
  { cdg: "IGM", name: "Índice Geral de Preços de Mercado" },
  { cdg: "GBP", name: "Libra Esterlina" },
  { cdg: "ITL", name: "Lira Italiana" },
  { cdg: "DEM", name: "Marco Alemão" },
  { cdg: "TRD", name: "Taxa Referencial Diária" },
  { cdg: "UPC", name: "Unidade Padrão de Capital" },
  { cdg: "UPF", name: "Unidade Padrão de Financiamento" },
];
