export default [
  {
    cdg: "01",
    name: "Cobrança",
  },
  { cdg: "03", name: "Bloqueto Eletrônico" },
  { cdg: "04", name: "Conciliação Bancária" },
  { cdg: "05", name: "Débitos" },
  { cdg: "06", name: "Custódia de Cheques" },
  { cdg: "07", name: "Gestão de Caixa" },
  { cdg: "08", name: "Consulta/Informação Margem" },
  { cdg: "09", name: "Averbação da Consignação/Retenção" },
  { cdg: "10", name: "Pagamento Dividendos" },
  { cdg: "11", name: "Manutenção da Consignação" },
  { cdg: "12", name: "Consignação de Parcelas" },
  { cdg: "13", name: "Glosa da Consignação (INSS)" },
  { cdg: "14", name: "Consulta de Tributos a pagar" },
  { cdg: "20", name: "Pagamento Fornecedor" },
  { cdg: "22", name: "Pagamento de Contas, Tributos e Impostos" },
  { cdg: "25", name: "Compror" },
  { cdg: "26", name: "Compror Rotativo" },
  { cdg: "29", name: "Alegação do Sacado" },
  { cdg: "30", name: "Pagamento Salários" },
  { cdg: "32", name: "Pagamento de honorários" },
  { cdg: "33", name: "Pagamento de bolsa auxílio" },
  {
    cdg: "34",
    name: "Pagamento de prebenda (remuneração a padres e sacerdotes)",
  },
  { cdg: "40", name: "Vendor" },
  { cdg: "41", name: "Vendor a Termo" },
  { cdg: "50", name: "Pagamento Sinistros Segurados" },
  { cdg: "60", name: "Pagamento Despesas Viajante em Trânsito" },
  { cdg: "70", name: "Pagamento Autorizado" },
  { cdg: "75", name: "Pagamento Credenciados" },
  { cdg: "77", name: "Pagamento de Remuneração" },
  { cdg: "80", name: "Pagamento Representantes / Vendedores Autorizados" },
  { cdg: "90", name: "Pagamento Benefícios" },
];
